import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import { useSession, signIn, signOut } from "next-auth/react";

const LoginButton = () => {
  const { data: session } = useSession();
  if (session) {
    return (
      <>
        サインイン {session?.user?.email} <br />
        <button
          className="bg-blue-600 hover:bg-blue-500 text-white rounded px-4 py-2"
          onClick={() => signOut()}
        >
          ログアウト
        </button>
      </>
    );
  }
  return (
    <>
      未ログイン <br />
      <button
        className="bg-blue-600 hover:bg-blue-500 text-white rounded px-4 py-2"
        onClick={() => signIn()}
      >
        ログイン
      </button>
    </>
  );
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <LoginButton></LoginButton>
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </main>
    </>
  );
};

export default Home;
